name: ubiquitous-vis
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.12
  - numpy==1.26.4
  - pandas==1.4.2
  - matplotlib=3.5.3 #matplotlib==3.7.5
  - nibabel==4.0.1
  - nilearn==0.9.1
  - statsmodels=0.13.5
  - scikit-learn=1.5.2
  - h5py
  - ipykernel
  - seaborn==0.12.0
  - pip
  - r-base=4.3.3
  - r-lme4
  - r-lmerTest
  - r-matrix
  - r-ggplot2
  - r-stringr
  - r-dplyr
  - r-tidyr
  - r-broom
  - r-pbkrtest
  - r-emmeans
  - rpy2

  - pip:
    - cca-zoo==2.6.0
    - himalaya==0.4.2
    - torch==2.1.2
    - voxelwise_tutorials
    - pymer4
    - brainiak
    - statannotations
    - tabulate
    - imageio
  
